### ISSUE TITLE
A couple of notes on consistency of the examples

### ISSUE THREAD

**Issue by stfdxv** [mattm/sql-style-guide#5]
First of all thanks for the style guide.
At last someone saved my pinkie from holding shift for ages.

1) If this is a good example
```sql
-- Good
select
    id,
    email
from users
```
then why this is also a good one?
```sql
-- Good
select id, email
from users
where email like '%@gmail.com'
```
2) Not all examples have 'good/bad' lable.
For example in `Indenting where conditions`.

**Comment by mattm** [comment]
Great call on both of these, just fixed.
